
drop table despesa;
drop table conta;
drop table usuario;


create table conta (id number(19,0) generated as identity, icone varchar2(255 char), nome varchar2(255 char), saldo_inicial number(38,2), primary key (id));
create table despesa (id number(19,0) generated as identity, data date not null, descricao varchar2(255 char), valor number(38,2) not null check (valor>=0), conta_id number(19,0), primary key (id));
create table usuario (id number(19,0) generated as identity, email varchar2(255 char), nome varchar2(255 char), senha varchar2(255 char), primary key (id));
alter table despesa add constraint FKlngcgagha9t0c6n5kgqw4ut8g foreign key (conta_id) references conta;
create table conta (id number(19,0) generated as identity, icone varchar2(255 char), nome varchar2(255 char), saldo_inicial number(38,2), primary key (id));
create table despesa (id number(19,0) generated as identity, data date not null, descricao varchar2(255 char), valor number(38,2) not null check (valor>=0), conta_id number(19,0), primary key (id));
create table usuario (id number(19,0) generated as identity, email varchar2(255 char), nome varchar2(255 char), senha varchar2(255 char), primary key (id));
alter table despesa add constraint FKlngcgagha9t0c6n5kgqw4ut8g foreign key (conta_id) references conta;
create table conta (id number(19,0) generated as identity, icone varchar2(255 char), nome varchar2(255 char), saldo_inicial number(38,2), primary key (id));
create table despesa (id number(19,0) generated as identity, data date not null, descricao varchar2(255 char), valor number(38,2) not null check (valor>=0), conta_id number(19,0), primary key (id));
create table usuario (id number(19,0) generated as identity, email varchar2(255 char), nome varchar2(255 char), senha varchar2(255 char), primary key (id));
alter table despesa add constraint FKlngcgagha9t0c6n5kgqw4ut8g foreign key (conta_id) references conta;
create table conta (id bigint generated by default as identity, icone varchar(255), nome varchar(255), saldo_inicial numeric(38,2), primary key (id));
create table despesa (id bigint generated by default as identity, data date not null, descricao varchar(255), valor numeric(38,2) not null check (valor>=0), conta_id bigint, primary key (id));
create table usuario (id bigint generated by default as identity, email varchar(255), nome varchar(255), senha varchar(255), primary key (id));
alter table if exists despesa add constraint FKlngcgagha9t0c6n5kgqw4ut8g foreign key (conta_id) references conta;
